# Generated by Django 3.1.4 on 2023-04-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phobe',
            new_name='phone',
        ),
    ]
